version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    labels: ["dependencies", "ci"]
    assignees: ["ehabSaad01"]
    reviewers: ["ehabSaad01"]
