blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/ehabSaad01/sogeti-senior-cloud-engineer/security/advisories
    about: Please report vulnerabilities privately.
