variable "rg_name"       { type = string }
variable "location"      { type = string }
variable "vnet_rg"       { type = string }
variable "vnet_name"     { type = string }
variable "subnet_name"   { type = string }
variable "vm_name"       { type = string }
variable "vm_size"       { type = string }
variable "linux_username"{ type = string }
variable "ssh_pub_key"   { type = string }
variable "uami_name"     { type = string }
variable "dcr_rg"        { type = string }
variable "dcr_name"      { type = string }
